name: Shim Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Shim
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and test
        working-directory: shim
        run: docker compose run --rm test

      - name: Cleanup
        if: always()
        working-directory: shim
        run: docker compose down
