name: Shim Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Shim on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "ubuntu-latest"
          - "ubuntu-24.04-arm"
          - "windows-latest"
          - "macos-latest"
          - "macos-15-intel"
        include:
          - platform: "ubuntu-latest"
            vcpkg_triplet: "x64-linux"
          - platform: "ubuntu-24.04-arm"
            vcpkg_triplet: "arm64-linux"
          - platform: "windows-latest"
            vcpkg_triplet: "x64-windows-static"
          - platform: "macos-latest"
            vcpkg_triplet: "arm64-osx"
          - platform: "macos-15-intel"
            vcpkg_triplet: "x64-osx"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install CMake 3.31
        if: matrix.platform != 'ubuntu-24.04-arm'
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.31.x"

      - name: Install CMake 3.31 for ARM
        if: matrix.platform == 'ubuntu-24.04-arm'
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.31.8/cmake-3.31.8-linux-aarch64.tar.gz
          tar -xzf cmake-3.31.8-linux-aarch64.tar.gz
          sudo mv cmake-3.31.8-linux-aarch64 /opt/cmake
          echo "/opt/cmake/bin" >> $GITHUB_PATH

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git -b 2025.03.19
          cd vcpkg && ./bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=${{github.workspace}}/vcpkg" >> $GITHUB_ENV
          echo "${{github.workspace}}/vcpkg" >> $GITHUB_PATH
          ./vcpkg integrate install
        shell: bash

      - name: Install OpenMP
        if: startsWith(matrix.platform, 'macos')
        run: |
          brew install libomp

      - name: Configure CMake
        run: |
          cmake -S ${{github.workspace}}/shim -B ${{github.workspace}}/shim/build \
            -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=${{matrix.vcpkg_triplet}} \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: bash

      - name: Build
        run: cmake --build ${{github.workspace}}/shim/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/shim/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
